name: SLfM
channels:
  - anaconda
  - conda-forge
  - pytorch
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - absl-py=0.12.0
  - aiohttp=3.7.4
  - appdirs=1.4.4
  - async-timeout=3.0.1
  - attrs=20.3.0
  - audioread=2.1.9
  - blas=1.0
  - blinker=1.4
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - c-ares=1.17.1
  - ca-certificates=2022.6.15
  - cachetools=4.2.1
  - certifi=2022.6.15
  - cffi=1.14.5
  - chardet=4.0.0
  - click=7.1.2
  - cloudpickle=1.6.0
  - cryptography=3.4.6
  - cudatoolkit=11.3.1
  - cycler=0.10.0
  - cytoolz=0.11.0
  - dask-core=2.30.0
  - dbus=1.13.18
  - decorator=4.4.2
  - einops=0.4.1
  - expat=2.2.10
  - ffmpeg=4.3.1
  - filelock=3.6.0
  - fontconfig=2.13.1
  - freetype=2.10.4
  - gettext=0.19.8.1
  - glib=2.68.0
  - glib-tools=2.68.0
  - gmp=6.2.1
  - gnutls=3.6.13
  - google-auth=1.24.0
  - google-auth-oauthlib=0.4.1
  - grpcio=1.36.1
  - gst-plugins-base=1.14.0
  - gstreamer=1.14.0
  - h5py=2.10.0
  - hdf5=1.10.6
  - icu=58.2
  - idna=2.10
  - imageio=2.9.0
  - intel-openmp=2020.2
  - joblib=1.0.1
  - jpeg=9b
  - kiwisolver=1.3.1
  - kornia=0.6.7
  - krb5=1.18.2
  - lame=3.100
  - lcms2=2.11
  - ld_impl_linux-64=2.35.1
  - libblas=3.9.0
  - libcblas=3.9.0
  - libcurl=7.71.1
  - libedit=3.1.20191231
  - libffi=3.3
  - libflac=1.3.3
  - libgcc-ng=9.3.0
  - libgfortran-ng=9.3.0
  - libgfortran5=9.3.0
  - libglib=2.68.0
  - libgomp=9.3.0
  - libiconv=1.16
  - liblapack=3.9.0
  - libllvm10=10.0.1
  - libogg=1.3.4
  - libopus=1.3.1
  - libpng=1.6.37
  - libprotobuf=3.15.6
  - libsndfile=1.0.31
  - libssh2=1.9.0
  - libstdcxx-ng=9.3.0
  - libtiff=4.1.0
  - libuuid=2.32.1
  - libuv=1.41.0
  - libvorbis=1.3.7
  - libxcb=1.13
  - libxml2=2.9.10
  - llvmlite=0.36.0
  - loguru=0.5.3
  - lz4-c=1.9.3
  - markdown=3.3.4
  - matplotlib-base=3.3.4
  - mkl=2020.2
  - mkl-service=2.3.0
  - mkl_fft=1.3.0
  - mkl_random=1.2.0
  - multidict=5.1.0
  - ncurses=6.2
  - nettle=3.6
  - networkx=2.5
  - ninja=1.10.2
  - numba=0.53.0
  - numpy=1.19.2
  - numpy-base=1.19.2
  - oauthlib=3.0.1
  - olefile=0.46
  - openh264=2.1.1
  - openssl=1.1.1o
  - packaging=20.9
  - pcre=8.44
  - pillow=8.1.2
  - pip=21.0.1
  - pooch=1.3.0
  - protobuf=3.15.6
  - pthread-stubs=0.4
  - pyasn1=0.4.8
  - pyasn1-modules=0.2.7
  - pycparser=2.20
  - pyjwt=2.0.1
  - pyopenssl=20.0.1
  - pyparsing=2.4.7
  - pyqt=5.9.2
  - pysocks=1.7.1
  - pysoundfile=0.10.3.post1
  - python=3.8.8
  - python-dateutil=2.8.1
  - python_abi=3.8
  - pytorch=1.12.1
  - pytorch-mutex=1.0
  - pywavelets=1.1.1
  - pyyaml=5.3.1
  - qt=5.9.7
  - readline=8.0
  - requests-oauthlib=1.3.0
  - resampy=0.2.2
  - rsa=4.7.2
  - scikit-image=0.17.2
  - scikit-learn=0.24.1
  - scipy=1.6.1
  - setuptools=49.6.0
  - sip=4.19.13
  - six=1.15.0
  - sqlite=3.34.0
  - tensorboard=2.4.1
  - tensorboard-plugin-wit=1.8.0
  - threadpoolctl=2.1.0
  - tifffile=2020.10.1
  - tk=8.6.10
  - toolz=0.11.1
  - torchaudio=0.12.1
  - torchvision=0.13.1
  - tornado=6.1
  - tqdm=4.59.0
  - urllib3=1.26.4
  - werkzeug=1.0.1
  - wheel=0.36.2
  - x264=1!161.3030
  - xorg-libxau=1.0.9
  - xorg-libxdmcp=1.1.3
  - xz=5.2.5
  - yaml=0.2.5
  - yarl=1.6.3
  - zipp=3.4.1
  - zlib=1.2.11
  - zstd=1.4.9
  - pip:
    - alabaster==0.7.12
    - alembic==1.8.1
    - altair==4.2.2
    - amqp==5.1.1
    - antlr4-python3-runtime==4.8
    - automaton==3.0.1
    - autopage==0.5.1
    - av==10.0.0
    - babel==2.9.0
    - backcall==0.2.0
    - backports-zoneinfo==0.2.1
    - bagpy==0.4.4
    - bcrypt==4.0.0
    - bitstring==3.1.7
    - brotli==1.0.9
    - catkin-pkg==0.4.23
    - charset-normalizer==2.1.1
    - cliff==4.0.0
    - cmd2==2.4.2
    - commonmark==0.9.1
    - cython==0.29.23
    - dataclasses==0.6
    - debtcollector==2.5.0
    - distro==1.5.0
    - dnspython==2.2.1
    - docker==6.0.0
    - docutils==0.16
    - dogpile-cache==1.1.8
    - entrypoints==0.4
    - eventlet==0.33.1
    - extras==1.0.0
    - facenet-pytorch==2.5.2
    - fairseq==0.10.2
    - fasteners==0.17.3
    - fixtures==4.0.1
    - future==0.18.2
    - futurist==2.4.1
    - gitdb==4.0.10
    - gitpython==3.1.30
    - gnupg==2.3.1
    - greenlet==1.1.3
    - hydra-core==1.0.6
    - imagesize==1.2.0
    - importlib-metadata==4.12.0
    - importlib-resources==5.1.2
    - ipython==7.22.0
    - ipython-genutils==0.2.0
    - iso8601==1.0.2
    - jedi==0.18.0
    - jinja2==2.11.3
    - jmespath==1.0.1
    - jsonpatch==1.32
    - jsonpointer==2.3
    - jsonschema==4.15.0
    - keystoneauth1==5.0.0
    - keystonemiddleware==10.1.0
    - kombu==5.2.4
    - librosa==0.8.1
    - livereload==2.6.3
    - logutils==0.3.5
    - lunr==0.5.8
    - m2r2==0.2.7
    - magnum==14.0.0
    - mako==1.2.2
    - marathon==0.13.0
    - markdown-it-py==2.1.0
    - markupsafe==1.1.1
    - matplotlib==3.2.1
    - mdurl==0.1.2
    - mistune==0.8.4
    - mkdocs==1.1.2
    - msgpack==1.0.4
    - munch==2.5.0
    - mutagen==1.46.0
    - netaddr==0.8.0
    - netifaces==0.11.0
    - nltk==3.5
    - omegaconf==2.0.6
    - opencv-contrib-python==4.5.1.48
    - openstacksdk==0.101.0
    - os-client-config==2.1.0
    - os-service-types==1.7.0
    - osc-lib==2.6.2
    - oslo-cache==3.1.0
    - oslo-concurrency==5.0.0
    - oslo-config==9.0.0
    - oslo-context==5.0.0
    - oslo-db==12.1.0
    - oslo-i18n==5.1.0
    - oslo-log==5.0.0
    - oslo-messaging==14.0.0
    - oslo-metrics==0.5.0
    - oslo-middleware==5.0.0
    - oslo-policy==4.0.0
    - oslo-reports==2.4.0
    - oslo-serialization==5.0.0
    - oslo-service==3.0.0
    - oslo-upgradecheck==2.0.0
    - oslo-utils==6.0.1
    - oslo-versionedobjects==3.0.1
    - pandas==1.2.3
    - parso==0.8.2
    - paste==3.5.2
    - pastedeploy==2.1.1
    - pathlib==1.0.1
    - pbr==5.10.0
    - pecan==1.4.2
    - pedalboard==0.3.8
    - pexpect==4.8.0
    - pickleshare==0.7.5
    - pkgutil-resolve-name==1.3.10
    - portalocker==2.0.0
    - prettytable==3.4.1
    - progressbar==2.5
    - prometheus-client==0.14.1
    - prompt-toolkit==3.0.18
    - psutil==5.8.0
    - ptyprocess==0.7.0
    - py3rosmsgs==1.18.1
    - pyarrow==11.0.0
    - pycadf==3.1.1
    - pycryptodomex==3.10.1
    - pydash==5.0.0
    - pydeck==0.8.0
    - pydot==1.4.2
    - pygments==2.14.0
    - pyinotify==0.9.6
    - pymdown-extensions==8.1.1
    - pympler==1.0.1
    - pyperclip==1.8.2
    - pyrealsense2==2.43.0.3018
    - pyrsistent==0.18.1
    - pyserial==3.5
    - python-barbicanclient==5.4.0
    - python-cinderclient==9.1.0
    - python-glanceclient==4.1.0
    - python-heatclient==3.1.0
    - python-keystoneclient==5.0.1
    - python-neutronclient==8.1.0
    - python-novaclient==18.1.0
    - python-octaviaclient==3.0.0
    - python-openstackclient==6.0.0
    - python-swiftclient==4.1.0
    - pytz==2021.1
    - pytz-deprecation-shim==0.1.0.post0
    - recommonmark==0.7.1
    - regex==2021.3.17
    - repoze-lru==0.7
    - requests==2.28.1
    - requests-toolbelt==0.9.1
    - requestsexceptions==1.4.0
    - rfc3986==2.0.0
    - rich==13.3.1
    - rinoh-typeface-dejavuserif==0.1.3
    - rinoh-typeface-texgyrecursor==0.1.1
    - rinoh-typeface-texgyreheros==0.1.1
    - rinoh-typeface-texgyrepagella==0.1.1
    - rinohtype==0.5.2
    - rospkg==1.3.0
    - routes==2.5.1
    - sacrebleu==1.5.1
    - seaborn==0.11.1
    - semver==2.13.0
    - simplegeneric==0.8.1
    - simplejson==3.17.6
    - smmap==5.0.0
    - snowballstemmer==2.1.0
    - sphinx==3.2.1
    - sphinx-autodoc-typehints==1.4.0
    - sphinx-bootstrap-theme==0.7.1
    - sphinx-markdown-parser==0.2.4
    - sphinx-rtd-theme==0.5.1
    - sphinxcontrib-applehelp==1.0.2
    - sphinxcontrib-devhelp==1.0.2
    - sphinxcontrib-htmlhelp==1.0.3
    - sphinxcontrib-jsmath==1.0.1
    - sphinxcontrib-qthelp==1.0.3
    - sphinxcontrib-serializinghtml==1.1.4
    - sqlalchemy==1.4.40
    - sqlalchemy-migrate==0.13.0
    - sqlparse==0.4.2
    - statsd==3.3.0
    - stevedore==4.0.0
    - streamlit==1.17.0
    - taskflow==5.0.0
    - tempita==0.5.2
    - tenacity==8.0.1
    - testresources==2.0.1
    - testscenarios==0.5.0
    - testtools==2.5.0
    - toml==0.10.2
    - torchlibrosa==0.0.7
    - traitlets==5.0.5
    - typing-extensions==4.4.0
    - tzdata==2022.7
    - tzlocal==4.2
    - unify==0.5
    - untokenize==0.1.1
    - validators==0.20.0
    - vine==5.0.0
    - voicefixer==0.1.2
    - warlock==2.0.1
    - watchdog==2.2.1
    - wavencoder==0.1.2
    - wcwidth==0.2.5
    - webob==1.8.7
    - websocket-client==1.4.1
    - websockets==10.4
    - wrapt==1.14.1
    - wsme==0.11.0
    - yapf==0.31.0
    - yappi==1.3.6
    - yt-dlp==2023.1.6
    - ytsphinx==1.2.1.dev20200430
